### ISSUE TITLE
Problem z metodą howClose

### ISSUE THREAD

**Issue by 11xTrashx11** [SocketByte/OpenSectors#4]
Zawsze zwraca Double.MAX_VALUE, ps. config nie były zmieniany (na bungeecord).

**Comment by SocketByte** [comment]
Skopiuj konfigurację z githuba, standardowa nie działa.

**Comment by 11xTrashx11** [comment]
Ok, działa a mógłbyś jeszcze libki wstawić bo nie każdy mavena używa ;p

**Comment by SocketByte** [comment]
To używaj, maven to żaden problem, a ułatwia życie.
