### ISSUE TITLE
Złe ustawianie worldborder

### ISSUE THREAD

**Issue by 11xTrashx11** [SocketByte/OpenSectors#5]
Po przejsciu z sektora center na inny jestem za granicą i zaczyna mnie bić. Najwidoczniej center granicy jest ustawiane na koordynaty x:0, z:0

**Comment by krzysiekigry** [comment]
`        log().info("Applying world border...");
        World world = Bukkit.getWorlds().get(0);

        WorldBorder worldBorder = world.getWorldBorder();
        worldBorder.setSize((config.border - 25) * 2); // im genius XD
        worldBorder.setCenter(0, 0);
        log().info("Ready!");`
Każdy sektor robi granice (1500 - 25 * 2) czyli 1475 jest border na każdym sektorze jest to granica ogólna aktualnie nie ma tak jak jest to na serwerach mc że każdy sektor ma własny border (wszystkie sektory mają granice na 1475 obojętnie który to)

**Comment by 11xTrashx11** [comment]
nie wiesz o co mi chodzi, gdy center jest zawsze ustawiony na 0, 0 wtedy po przejsciu z center na inny zaczyna cie bić granica bo jesteś za nią. Dlatego wypadałoby ustawić setCenter na x i z środka danego sektora

**Comment by krzysiekigry** [comment]
Jak możesz być poza granicą jak granica na każdym sektorze jest ustawiona na 1475 a za nią sektorów nie ma chyba ze masz jakąś dziwna granice w configu ... Dobra wiem zmień w configu buneecorda border **(  "border": 1500,)**  na tyle ustaw

**Comment by 11xTrashx11** [comment]
Never mind myslalem, ze kazdy serwer ma inny border
