### ISSUE TITLE
Pytanie

### ISSUE THREAD

**Issue by bananekdev** [SocketByte/OpenSectors#6]
Jak mogę pobrać inventory od gracza życie itp. który znajduje się na innym sektorze?

**Comment by krzysiekigry** [comment]
https://github.com/SocketByte/OpenSectors/blob/master/OpenSectorLinker/src/main/java/pl/socketbyte/opensectors/linker/packet/PacketPlayerInfo.java

**Comment by bananekdev** [comment]
no tak ale jak mam pobrac bo w PlayerInfoHolder sa pakiety tylko z sektora na ktorym cos zostalo wykonane

**Comment by SocketByte** [comment]
Teoretycznie nie jest to taka łatwa rzecz. Musisz stworzyć pakiet używając `PacketExtender` (po stronie proxy) który będzie zawierać: uuid gracza, wolne miejsce na `PacketPlayerInfo` i miejsce na `sectorId`, później z tego pakietu (który dostaniesz od linkera do proxy) pobierasz te uuid gracza, oraz sektor na którym się znajduje (`LinkerStorage#getLinkerByPlayer`). Później najprościej będzie odsyłać tą informację do tego sektora, tam uzupełniać `PacketPlayerInfo` (`new PacketPlayerInfo(player, x, y`) i odsyłać tą informację do proxy, które wyśle ten pakiet z powrotem na serwer z którego wysyłałeś pakiet. Pamiętaj żeby w proxy jakoś sprawdzać czy to jest pakiet wychodzący/przychodzący, np. `packet.getPlayerInfo() == null`, to wtedy będzie oznaczać że masz się "uprosić" sektor o informacje. I oczywiście wysyłasz ten pakiet z callbackiem, czyli tak jak np. `PacketPlayerState`.
Jakbyś miał jakieś problemy, zapraszam serdecznie na discorda który masz w README. Życzę powodzenia. :) W przyszłości może spróbuję podobny pakiet wykonać.

**Comment by bananekdev** [comment]
Ok, dziękuję za pomoc spróbuję coś takiego zrobić.
