### ISSUE TITLE
Null

### ISSUE THREAD

**Issue by bananekdev** [SocketByte/OpenSectors#7]
Robię randomtp i metoda w klasie Sector (getAt(location)) zwraca za kazdym razem nulla gdy stworzę randomową lokalizacje (pomiędzy x, z sektorów które są włączone). Nie musiałbym się bawić w getAt gdyby automatycznie po ruszeniu się przenosiło gracza na ten sektor ;p

**Comment by SocketByte** [comment]
Niee, nie używaj tych metod.
Po 1. Używaj do tego `PacketPlayerTeleport`
Po 2. `Nie musiałbym się bawić w getAt gdyby automatycznie po ruszeniu się przenosiło gracza na ten sektor ;p` ale to tak działa. Na pewno masz najnowszą wersję? I czy ten sektor jest aby na pewno odpalony?

**Comment by bananekdev** [comment]
wszystko właśnie powinno działać bo mam chyba z 10 sektorów, co do packetplayerteleport najwyżej dopisze zapisywanie podstawowych rzeczy np. życie, inventory, enderchest itp. Mam jeszcze jedno pytanie jeśli mam 2 sektory o tym samym center czyli np. 2 sektory spawna to jak mógłbym zrobić, że po przeniesieniu na 2 sektor spawna nie przenosiło znów na ten 1?

**Comment by SocketByte** [comment]
Sektory obecnie nie wspierają systemu channeli, czyli nie możesz.

**Comment by bananekdev** [comment]
Ok.

**Comment by DaanielZ** [comment]
Nie testowałem tego, ale zwykłe randomtp napisany na spigocie powinno działać ;d
