### ISSUE TITLE
Pytanie

### ISSUE THREAD

**Issue by mati12844** [SocketByte/OpenSectors#9]
Czy tylko src całego pluginu? Czy jakieś link do pobrania???

**Comment by mati12844** [comment]
I czy jest jakoś wytłumaczanie jak to mam wpierd*lić te src do eclipse. Bo gdy wrzucam src to pisze że jest juz taka nazwa i musze zmienaic i nie wiem czy to bedzie działać i jakie maja byc - jar w pluginach

**Comment by vellde** [comment]
Możesz pobrać: https://github.com/SocketByte/OpenSectors/releases

**Comment by mati12844** [comment]
Z góry dziękuje nie ogarniam tego githuba.
